debug: false

console:
    options:
        help:
            command:     ["help", "h"]   # ["longname", "shortname"]
            argument:    false
            description: "show help"     # description of command (displayed for help)
            required:    false           # optional

        logfile:
            command:     ["logfile", "f"]
            argument:    string          # checks type
            description: "logfile with sprintf-formatstring (see: http://php.net/manual/de/function.strftime.php)"
            config:      logfile.file    # config key, sets/replaces value
            required:    true

        symlink:
            command:     ["symlink", "s"]
            argument:    string
            description: "symlink location"
            config:      logfile.symlink
            required:    false

        cycle:
            command:     ["cycle"]
            type:        integer
            description: "how often to trigger a monitoring notification"
            config:      cycle
            required:    false

        host:
            command:     ["host"]
            type:        string
            description: "host to be monitored, monitoring data will be send to given host"
            config:      zabbix.host
            required:    false

        rotation:
            command:     ["precise-rotation"]
            description: "enable precise logfile rotation (check for rotation condition at every logline)"

        parser:
            command:     ["parser"]
            description: "ApacheErrorLog: parse ncsa/apache access logs"
            type:        string

        debug:
            command:     ["debug"]
            description: "debug output"
            argument:    false
            config:      debug

cycle:  300 # 5min

logfile:
    file:     "rz_access_log.%Y%m%d"
    symlink:  "rz_access_log-current" # string | false
    rotation: "precise"

zabbix:
    server:
        host: "monitoring.domain.tld"
        port: 10051
        timeout:
            connection: 2 # seconds
            stream:     5 # seconds

    host:      "test"
    heartbeat: true
