logfile:
    class: "LogfileBundle\\Listener\\LogfileListener"
    tags:
      - { event: "input", method: "input", priority: 1 }

# event "logged" is fired by logfile
zabbix:
    class: "ZabbixBundle\\Listener\\ZabbixListener"
    tags:
      - { event: "logged", method: "input", priority: 2 }
