#!/usr/bin/env php

<?php

$stub       = 'webserver_logpipe.php';
$projectDir = realpath(__DIR__ . '/..');
$file       = sprintf('%s/bin/logpipe.phar', $projectDir);

if(file_exists($file)) :

    unlink($file);
endif;

$phar = new Phar($file, FilesystemIterator::CURRENT_AS_FILEINFO | FilesystemIterator::KEY_AS_FILENAME, 'logpipe.phar');
$phar->buildFromDirectory($projectDir);
$phar->setStub($phar->createDefaultStub($stub));